### PR TITLE
Fix duplicate rendering in _configureTreeColumn #Fixes 1157

### PR DESCRIPTION
**Pull request by maier49**
This fix is essentially what was suggested in the original issue, with the slight modification that we're also removing any event handlers that are lingering about when `_configureTreeColumns` is called multiple times. That doesn't actually manifest itself in the provided test case because the whole grid is refreshed but if it was being called multiple times without refreshing the grid additional event handlers are added without cleaning up the existing ones.

### CODE REVIEW

**Comment by maier49** [comment]
Here's a JSFiddle demonstrating the fix: http://jsfiddle.net/6rq1y3gh/

**Comment by kfranqueiro** [comment]
Would you mind moving the new test into `mixins/Tree` which already exists?

I'm also wondering whether we can think of a solution other than storing `originalRenderCell` on the column object.  That feels a little risky to me since you could argue that if Editor and Tree acted consistently, they'd overwrite each other.  (For that matter, I have to wonder whether we have similar issues over-overriding `renderCell` in Editor and Selector, just less noticeable?)

**Comment by maier49** [comment]
I moved the test case and changed it to use `isConfiguredTreeColumn` as a flag on the column definition, so that any other modules that need similar logic applied could set their own flags so that they wouldn't interfere. Unless of course they are overriding the function without calling the original at all, but that seems like it's outside the scope of this fix.

**Comment by kfranqueiro** [comment]
Upon reviewing this I noticed the test case could be reduced to fit into one of the existing suites, and I made it test using a public API.  I also removed the `else` that was added since what it was doing is already done in `_destroyColumns`.

Manually backported to 0.4 due to conflicts, which ultimately I realized were just due to changes to remove `put-selector`.

**Comment by kfranqueiro** [comment]
Also, RE my earlier concern, AFAICT Selector won't exhibit any issues like this since it completely overrides `renderCell` without calling the original.  I wasn't able to notice any particular issues trying Editor with ColumnReorder, either (IIRC the only time it could possibly be a concern would be when `editOn` is set).

**Pull request closed without merging**
