### PR TITLE
Use 'requestIdleCallback' when available for debounce/throttle

### LINKED ISSUE #1351: Browser scroll performance optimization can delay OnDemandList rendering
dgrid's `OnDemandList` uses debouncing or throttling to optimize rendering performance during scrolling. The debounce and throttle implementations are dependent on `setTimeout`, which has been targeted by [browser vendors](https://bugs.chromium.org/p/chromium/issues/detail?id=633188) for "optimization", which means the callback passed to `setTimeout` may be executed long after the specified delay.

This has been observed impacting moderately complicated grids in Chrome on MacOS.  The result is that when you perform a large rapid scroll, when you stop scrolling there is a significant delay (2-10 seconds) before the `setTimeout` callback is executed, data is fetched and rows are rendered.

### PR DESCRIPTION
**Pull request by msssk**
Fixes #1351

### CODE REVIEW

**Comment by msssk** [comment]
This is a severe problem in affected configurations, so I cherry-picked this commit and create a [PR for 0.4](https://github.com/SitePen/dgrid/pull/1353) as well.

To reproduce, simply scroll through an `OnDemandGrid` with Chrome 56. Scroll rapidly using the mousewheel. Normal behavior is you see the grid is blank while scrolling, but as soon as you stop it is almost instantly populated with rows. New behavior in Chrome 56 is that there is a significant delay before the rows are rendered. If `pagingMethod` is set to `throttle` the rows are never rendered.

This may be dependent on the grid complexity - I have a test case I can share on request.

**Comment by bryanforbes** [comment]
Couldn't we abstract the decision between `setTimeout` and `requestIdleCallback` earlier in the module and use the abstraction instead? For instance:

```js
var delayCallback;
var cancelDelay;

if (has('requestidlecallback')) {
    delayCallback = function (callback, delay) {
        return requestIdleCallback(callback, { timeout: delay });
    };
    cancelDelay = cancelIdleCallback;
}
else {
    delayCallback = setTimeout;
    cancelDelay = clearTimeout;
}
```

Then the implementations of `throttle`, `throttleDelayed`, and `debounce` would use `delayCallback()` and `cancelDelay()`.

**Comment by msssk** [comment]
I'm sold on Bryan's suggestion - performance impact of a single extra layer of function invocation is likely to be negligible. PR updated.

**Comment by edhager** [comment]
Thanks @msssk!

**Pull request closed without merging**
