### PR TITLE
Add text area and dijit form widgets as options for editor

### PR DESCRIPTION
**Pull request by maier49**

### CODE REVIEW

**Comment by kfranqueiro** [comment]
Upon discussing this PR, we came up with a few further items:

* Change editor and editOn inputs to FilteringSelect
* Auto-change dismissOnEnter based on whether textarea or SimpleTextarea is selected
* Fix duplicate dependencies if the same editor widget is used for multiple columns

**Comment by maier49** [comment]
The suggested changes have been implemented.

**Comment by kfranqueiro** [comment]
I made a couple of refinements to `toJavascript` on my branch.  I'm pretty sure it's fine, but if you want to take a look: https://github.com/kfranqueiro/dgrid/commit/fb553ca7346d40e38266ccdeaf9f66fea4d4b452

**Comment by kfranqueiro** [comment]
This has been merged via https://github.com/SitePen/dgrid/commit/9b40f94a89e8e6627b195a083cbe3338414eba9d (master) and https://github.com/SitePen/dgrid/commit/d37b4aad95f40515d513636bbd8627eda0673202 (dev-0.4). Thanks!

**Pull request closed without merging**
