### PR TITLE
Stylus refactor of dgrid CSS

### PR DESCRIPTION
**Pull request by dylans**
This is the work to refactor dgrid's CSS into Stylus. I have compared the generated CSS with the original CSS, as well as run through the test suite. A few notes:

To compile, make sure Stylus and nib are installed, and then run a command like this:
stylus skins/ --use nib

In an attempt to show the differences between each theme, the first 62 lines of each skins/*.styl file are in the same order, with unused rules commented out. Unfortunately, this is resulting in the commented out rules being preserved in the output CSS, unless we use the compressed version of Stylus' output (which may be a better option once this is reviewed). Otherwise, we would probably want to create a separate variables file for each theme, to prevent the comments from appearing in each CSS file for the unused rules. Or we could just remove the unused rules after the themes are evaluated.

default.styl is the full list of rules. A file like this may be useful for people creating a new theme, if it received a neutral set of rules

Some of the themes do not provide IE6-8 fallback gradients. Let me know if these should be added or not.

There are a couple of other TODOs for rules that don't make sense and should probably be removed.

Finally, my choice of names for variables isn't necessarily the best, but I tried to be consistent. That said, the underlying names are fairly inconsistent because we sometimes use the theme roller names, and sometimes our own. This exercise may make it easier to clean that up later. Hopefully by making each skin have a consistent variable structure, it will be easier to clean this up with perhaps more logical variable names.

Any other feedback or suggestions are greatly appreciated. This was my first significant work with Stylus, so I'm sure there are things I could be doing differently.

### CODE REVIEW

**Comment by kfranqueiro** [comment]
I have been working on a more maintainable conversion of the dgrid skins to stylus in my free time, which will supersede this PR.

**Comment by gaurav21r** [comment]
I think LESS is more future friendly now than Stylus. It has a lot more community backing behind it. We have taken a similar decision for JsDoc vs DojoDoc. Choosing the community over the more "advanced" technology.

I **strongly recommend** we stick with LESS for Dojo 2.0.

**Comment by dylans** [comment]
@gaurav21r unfortunately I disagree here, as it's not the same as a documentation format. There are at least a dozen major things with LESS that we've had bugs open on for years. It baffles me that LESS has gained more traction without a from the ground up rewrite of their code base. I invite you to review the source of both, and tell me that you do not see the difference in clarity and code quality. While we can accept compromise on a format or a syntax, we are not willing to sacrifice quality and architecture because of popularity.

**Comment by gaurav21r** [comment]
@dylans Can you please point me to these bugs? Also, are you talking about the code structure inside the project or the structure of the LESS language itself? My team and I have experience of creating at least 4 different themes based off of claro using less, as well as experience in projects involving bootstrap integration etc. I hope my experience can benefit Dojo's future regarding this call. That's why I'm being vocal about this issue.

**Comment by dylans** [comment]
@gaurav21r yes, I mean the actual source code of LESS vs. the source code of Stylus. I believe you would have been just as successful starting with dijit-claro-stylus.

As far as various bugs, I've answered this before, for example in http://mail.dojotoolkit.org/pipermail/dojo-interest/2013-January/073356.html as well as a few comments up at https://github.com/SitePen/dgrid/pull/758#issuecomment-37141149

What really pushed us over the edge was https://github.com/less/less.js/pull/331 , which was in our experience a very critical bug, and it took two years to really have it considered. That's when we found Stylus, which just worked.

There's also a discussion at http://dote.kitsonkelly.com/topic/f32e728a-d2d3-491a-8ff4-586c81ee506d where people have pointed out many of the nice features with regards to how Stylus does variables/mixins, vendor prefixing, CSS animations, etc.

It is very trivial to go from LESS to Stylus, but Stylus gives you a lot more flexibility.

Until you have built a theme with Stylus and have inspected the source code of both LESS and Stylus, it does not seem reasonable to champion for one over the other just because one is popular. We do not make key architectural decisions based on popularity. When we chose LESS, it was not popular, but it was the best option on the market. Today it is popular, but technically inferior.

**Comment by dylans** [comment]
@gaurav21r also, if you want to continue this debate, it should move to the dojo-interest mailing list, as this really isn't relevant to dgrid.

**Pull request closed without merging**
